name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  static-analysis:
    name: Execute analyse on code
    continue-on-error: false
    timeout-minutes: 5
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Lint
        run: ./gradlew lint

  build-and-test:
    name: Build and test
    continue-on-error: false
    timeout-minutes: 20
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 21, 24, 29, 31, 33 ]
        target: [ google_apis ]
    needs:
      - static-analysis

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Permission for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest

  generate-debug-apk:
    name: Generate debug APK
    timeout-minutes: 20
    runs-on: macos-latest
    needs:
      - build-and-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk