name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate-release-apk:
    name: Release APK
    timeout-minutes: 20
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore and Create Properties
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/release.keystore
          echo "storeFile=${{ github.workspace }}/release.keystore" > ${{ github.workspace }}/keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> ${{ github.workspace }}/keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> ${{ github.workspace }}/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ${{ github.workspace }}/keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Sign with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release/app-release.apk