#- name: Permission for gradlew
#  run: chmod +x gradlew

name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  static-analysis:
    name: Code Analysis
    continue-on-error: false
    timeout-minutes: 20
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Lint check
        run: ./gradlew lint

  unit-test:
    name: Unit Test
    continue-on-error: false
    timeout-minutes: 20
    runs-on: macos-latest
    needs:
      - static-analysis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  build-and-test:
    name: Instrumentation Test
    continue-on-error: false
    timeout-minutes: 20
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29, 31, 33 ]
        target: [ google_apis ]
    needs:
      - unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest

  generate-debug-apk:
    name: Debug APK
    timeout-minutes: 20
    runs-on: macos-latest
    needs:
      - build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  generate-release-apk:
    name: Release APK
    timeout-minutes: 20
    runs-on: macos-latest
    needs:
      - build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with gradle
        run: ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@v1.0.4
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}